### ISSUE TITLE
add line numbers

### ISSUE THREAD

**Issue by OmlineEditor** [FredHappyface/Android.FHCode#16]
please add line numbers in the editor. This way it will be more convenient to look for the error location when it is said that the problem is in the line number ###

**Comment by FredHappyface** [comment]
Just an update that this is well underway. I'd like to address a few of these features before doing a new release

**Comment by FredHappyface** [comment]
Gonna get this released over the weekend :)

**Comment by FredHappyface** [comment]
Added in https://github.com/FredHappyface/Android.FHCode/releases/tag/20240331
