### ISSUE TITLE
[Feature request] Please, include a compiler to run the code

### ISSUE THREAD

**Issue by moshpirit** [FredHappyface/Android.FHCode#2]

**Comment by FredHappyface** [comment]
> Please provide some more information with this issue/ merge request! Thanks 😊

Good bot

The templates are for actually filling in. Thanks

**Comment by moshpirit** [comment]
Sorry, I use FastHub-libre on my phone and it doesn't load templates. Will do on my laptop now

**Comment by FredHappyface** [comment]
No worries, completely forgot that was a thing tbh
