### ISSUE TITLE
Feature: Support for NSIS language

### ISSUE THREAD

**Issue by SimoLRepo** [FredHappyface/Android.FHCode#21]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar feature requests in the project's issue tracker
  to avoid duplicates.
- [x] I have searched existing issues to see if this feature has been discussed
  before.

### Is your feature request related to a problem? Please describe

NSIS (Nullsoft Scriptable Install System) syntax highlighting is missing.

### Describe the solution you'd like

Hello, would it be possible to add support for NSIS (Nullsoft Scriptable Install System) syntax highlighting? Thank you very much.

### Describe alternatives you've considered

In the Android environment I tried others source code editors, including Acode, but they require too many system resources and are very slow during use.

### Additional Context

I typically use NSIS for software automation more than for creating simple installation packages.

<b><i>Some examples for syntax testing:</i></b>
<a href="https://nsis.sourceforge.io/Category:Code_Examples">https://nsis.sourceforge.io/Category:Code_Examples</a>

<b><i>Some examples for "Headers" files:</i></b>
<a href="https://nsis.sourceforge.io/Category:Headers">https://nsis.sourceforge.io/Category:Headers</a>

<b><i>File extensions of this language:</i></b>
*.nsi (scripts) / *.nsh (Headers files)

**Comment by SimoLRepo** [comment]
Although I opened a ticket as was indicated to me on the Google Play store and [filled out the form](https://github.com/FredHappyface/Android.FHCode/issues/15) I received no consideration. Among other things, the scrolling is not exceptionally responsive. I will continue to use Notepad++, goodbye.

**Comment by FredHappyface** [comment]
Yeah apologies for the delay, I've been super busy with life and stuff! If you've a preferred editor then that's cool. Thanks for taking the time to open the issue etc

It's not unusual on foss projects with limited resource (eg. a one person team like this one) to take a little while to get around to responding to issues
